clubs/urls.py
from django.urls import path

from . import views

app_name = 'clubs'
urlpatterns = [
    path("", views.ClubListView.as_view(), name="clubs"),
    path("new/", views.ClubFormView.as_view(), name='club-create'),
    path("<slug:slug>/", views.ClubView.as_view(), name="club"),
    path("<slug:slug>/<int:pk>", views.PickView.as_view(), name="pick"),
    path("<slug:slug>/new-pick/", views.PickFormView.as_view(), name="pick-create")
]

musekclub/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("clubs/", include("clubs.urls")),
]

clubs/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

# Create your models here.

CLUB_TYPE_CHOICES = (
    ('songs', 'Songs'),
    ('albums', 'Albums')
)

class Club(models.Model):
    name = models.CharField(
        verbose_name='name',
        max_length=50
    )
    slug = models.SlugField(
        verbose_name='slug',
        max_length=50,
        unique=True
    )
    tagline = models.CharField(
        verbose_name='tagline',
        max_length=60, 
        blank=True,
        null=True
    )
    club_type = models.CharField(
        verbose_name='club type',
        max_length=20,
        choices=CLUB_TYPE_CHOICES,
        default='songs'
    )
    members = models.ManyToManyField(User)
    create_date = models.DateTimeField(
        verbose_name='date created'
    )

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("clubs:club", args=[self.slug])


class Pick(models.Model):
    name = models.CharField(
        verbose_name='name',
        max_length=50
    )
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    url = models.URLField(
        verbose_name='url'
    )
    reason = models.CharField(
        verbose_name='reason',
        max_length=250
    )
    active = models.BooleanField(default=True)
    user = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL,
        null=True
    )
    created = models.DateTimeField(
        verbose_name='date created'
    )

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("clubs:club", args=[self.slug])
    

clubs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormView, CreateView

from .models import Club, Pick

from datetime import datetime


# Create your views here.
class ClubListView(LoginRequiredMixin, ListView):
    login_url = "/admin"
    template_name = 'clubs/clubs.html'
    def get_queryset(self):
        return Club.objects.filter(members=self.request.user)

class ClubView(LoginRequiredMixin, DetailView):
    model = Club
    template_name = 'clubs/club.html'

    # get and pass in picks related to club
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['picks'] = Pick.objects.filter(club=self.object).order_by('-created')
        return context
    
    # ensure user is in club to view it
    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if self.request.user in obj.members.all():
            return obj
        else:
            raise PermissionDenied
    

class ClubFormView(LoginRequiredMixin, CreateView):
    model = Club
    template_name = 'clubs/club_form.html'
    fields = [
        'name',
        'tagline',
        'club_type'
    ]

    def form_valid(self, form):
        # ensure unique slug
        slug = slugify(form.cleaned_data['name'])
        counter = 1
        while Club.objects.filter(slug=slug).exists():
            slug = f"{slug}-{counter}"
            counter += 1
        form.instance.slug = slug
        form.instance.create_date = datetime.now()
        form.save()
        # Auto-add member that created the group
        form.instance.members.add(self.request.user.id)     
        return super().form_valid(form)
    

class PickView(LoginRequiredMixin, DetailView):
    model = Pick
    template_name = 'clubs/pick.html'

class PickFormView(LoginRequiredMixin, CreateView):
    model = Pick
    template_name = 'clubs/pick_form.html'
    fields = [
        'name',
        'url',
        'reason'
    ]

    # get club and pass into form html
    def get_context_data(self, **kwargs):
        context = super(PickFormView, self).get_context_data(**kwargs)
        context['club'] = Club.objects.get(slug=self.kwargs['slug'])
        return context
    
    # set fields not exposed in the form
    def form_valid(self, form):
        form.instance.club = Club.objects.get(slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        form.instance.created = datetime.now()
        return super().form_valid(form)
    
    # allows for the club slug to be passed to the club url
    def get_success_url(self):
        return reverse_lazy('clubs:club', kwargs={'slug': self.kwargs['slug']})
    

clubs/templates/clubs/club.html
<h1>{{ club }}</h1>
<h2>{{ club.tagline }}</h2>
<h3>Club Type: {{ club.club_type|title }}</h3>
<span style="color:gray">Created {{ club.create_date }}</span>
<br/><br/>
Members:<br/>
{% for u in club.members.all %}
<li>{{ u.username }}</li>
{% endfor %}
<br/>
Picks:
<button><a href="{% url 'clubs:pick-create' club.slug %}">Pick</a></button>
{% for pick in picks %}
<li><a href="{{ pick.url }}" target="_blank">{{ pick }}</a></li>
{% endfor %}

clubs/templates/clubs/club_form.html
<form action="/clubs/new/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

clubs/templates/clubs/clubs.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Musek Clubs</title>
</head>
<body>

<button><a href="{% url 'clubs:club-create' %}">Create Club</a></button>


<h1>List of Clubs:</h1>
{% for club in object_list %}

<li><a href="{% url 'clubs:club' club.slug %}">{{club}}</a></li>

{% endfor %}

</body>
</html>

clubs/templates/clubs/pick.html
<h1>{{ pick }}</h1>
<h2>{{ pick.user.name }}</h2>
<h3>Listen: {{ pick.url }}</h3>
reason: {{ pick.reason }}
<span style="color:gray">Created {{ pick.created }}</span>

clubs/templates/clubs/pick_form.html
<form action="/clubs/{{ club.slug }}/new-pick/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>